### ISSUE TITLE
Training materials for power users on large database projects (not field methods classes, but longer term projects)

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#1400]
this is the close to final step for import:

"Annotation training using the spreadsheet app and new language data (~20 hrs); training on the codebase and organization of the app (~20 hrs)"

**Comment by louisa-bielig** [comment]
see #1224

Training plan for power users (5 hours of tutorials)

1. How to replicate data, (30 min)
i.e. how to make a copy of the data that can be changed without touching the original data, and can then be merged with the original data

2. How to work offline with replicated data (30 min)

3. How to see all of your data (30 min)

4.How to retroactively apply tags to data (30 min)

5. How to select a specific confidence range for cleaning (30 min)

6. How to select only data with certain properties/morphemes/tags (1h)
i.e. how to write a cleaning script & how to use regex 

7. How to change all data with certain properties/morphemes/tags (1h)
i.e. how to clean all data picked out by a cleaning script

8. How to undo previous changes (30 min)
i.e. version control

9. How to see what other people have changed (30 min)
i.e. time log for user activity

Additional lessons for fast learners:

1. How to import/export audio & video, images

2. How to detect utterances and create datums with audio/video

3. How to make syntax trees with LaTeX with LingSync data

4. How to export data to pdf

5. How to build language-learning lessons with data/audio/video
