### ISSUE TITLE
Tutorial on how to use Sublime Text 3

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#1542]
Sublime http://www.sublimetext.com/3 has many features that will help you check your javascript syntax here are some we use the most

* command D to rename variables
* Jshint (control J after you installed the plugin)
* format (command shift p, format after you installed the plugin)
* command / to toggle comments on a line
* command control and arrows to move lines up and down 

This issue is to find some youtube videos for sublime for interns

**Comment by louisa-bielig** [comment]
On some keyboards, command / (to toggle comments on a line) may not work. This can be fixed, as explained here:

http://www.sublimetext.com/forum/viewtopic.php?f=3&t=12195#p47972

**Comment by louisa-bielig** [comment]
Sublime Text 3 Setup, package control and settings:
https://www.youtube.com/watch?v=zVLJfrIwEP8

Multi Select:
https://www.youtube.com/watch?v=zVLJfrIwEP8

Multi-line cursors & incremental selecting:
https://www.youtube.com/watch?v=EzKS2UhZ76w
