### ISSUE TITLE
intellectual property ownership need to be more explicit

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#1906]
some notes from ICLDC presentation

- our agreements about intellectual property ownership need to be more explicit
  - maybe they are explicit, but I'm just ignorant of something
  - we talk about how corpus creators can license their corpora and make them
    public, but we're not explicit about who owns the data on our LingSync
    web service. (At least not to my knowledge.)
  - at any rate, more clairy on this point would be good

**Comment by cesine** [comment]
@jrwdunham I moved this to a seperate issue because its really important for people to find the answers to this question. it will always be an important question for any presentation, and needs to be super clear in the talk. Maybe you can add a slide about this to your deck in the future :)

We tried to be extra clear about this on the website https://www.lingsync.org/privacy.html and the details of how users should manage their corpora and sharing their corpus in the [CAML paper](https://github.com/OpenSourceFieldlinguistics/FieldDB/blob/master/docs/CAML/caml2012.pdf?raw=true)

Here is a copy:

Your data is your data.
In the spirit of transparency we provide you with these templates of standard social web app privacy policies and terms of service to fully explain the data involved in LingSync.org. There are two types:

* data which is typical data that most social websites use to make sure their app is user friendly and to let users trust each other and collaborate, and
* data which is your fieldlinguistics data (your "Corpus")

In both cases, we don't use your private data, and we have no partnerships with third parties. In fact, we try to avoid collecting any sensitive private data about you. We would also be happy to give you your private data, just request it.

However : we are a team of Open Source volunteers, as such we have no legal team, no customer support team and we want you to know that LingSync.org and the software that runs on it is provided AS IS, WITH NO WARENTEE, NO FORMAL SUPPORT AND NO GUARENTEE THAT IT WILL OR WILL NOT DO ANYTHING. If you are worried about these things, we prefer that you set up your own private server so that we don't have to worry about the legal implications of hosting your data.


If that isn't clear enough, please ask more and or help re-write it so its more clear.

**Comment by HughP** [comment]
What about derivative knowledge? how is that licensed? Perhaps we should skype so I can make myself clear.... I asked this question in one of the sessions at ILDC4 and @jrwdunham  was there, so @jrwdunham knows the trajectory I am headed when I ask this question.

**Comment by cesine** [comment]
oh hi @HughP  :) Sure we can skype, but this is one of the most fundamental questions which is one of the first questions users should ask, so why not make a public on air Hangout instead to be sure that everyone gets the same clear cut answer and has access to the conversation...

Maybe you are misunderstanding who is behind the app. We are field linguists, we don't want your data, we want our own data, and to be able to collaborate with our own complex teams. We will not accept anyone on the advisory board who we suspect has other interests or interests in accessing other people's data. 

Maybe you are confusing us with a granting and/or archiving institution, why would we care about what you do with your primary and or derivative knowledge? Granting institutions need to make sure they have licenses to do whatever they envision with the data collection they funded, so they might put licensing on your data. We have no such reason for this, except to let you slap whatever you license you want (or your funding agency wants) on the data, thats why every corpus can have its own license, terms and conditions etc. Have you visited Lingllama's sample page? It should be pretty clear that the license is his own choice... https://www.lingsync.org/lingllama/communitycorpus/lingllama-communitycorpus

What you do with your corpus is your own business, who you share it with, who you collaborate with is your business, by derivative knowledge if you mean building language learning apps, or publishing a dictionary, or publishing a research paper where the publisher requires some sort of exclusive license, that's your business. 

We see it as our responsibility to get out of the way so you can do whatever you want with your data at any time, including exporting it lock stock and barrel to an archive or to your granting agency, and/or use the REST API in real time to provide others with access to your data (eg for lang learning apps).

What can we do to help clarify this for you so that it's easier for users to understand this at a deeper level? Do we really need to add a clause about derivative knowledge?

**Comment by cesine** [comment]
@HughP I think it will be less work for us if we invite you to read access to the project so we can assign this issue to you, and you can help us with the wording via a pull request. we sent you an invite :)

* Link to [edit the sample terms of use which users can customize if they decided to make their corpus public](https://github.com/OpenSourceFieldlinguistics/AuthenticationWebService/edit/master/templates/public_corpus_template.js#L7)

* Link to [edit the privacy policy](https://github.com/OpenSourceFieldlinguistics/FieldDBWebServer/edit/master/public/privacy.html)

* Link to [edit the tutorial slides](https://docs.google.com/presentation/d/1GMRRvA9WLM--DiWyiWj6zlv3m4Cc4a3jcpPZDmi6Zmk/edit#slide=id.gc5fcd89f_159)

**Comment by jrwdunham** [comment]
@cesine A couple of initial comments (to your Mar 4 7:16pm post). 

First, we should run all our prose through a spellchecker. Could you make the following changes (probably faster than explaining to me how I can make them):

"WARENTEE" should be "WARRANTEE"
"GUARENTEE" should be "GUARANTEE"

Second, I think this Privacy page (https://www.lingsync.org/privacy.html) should be clearly linked from somewhere in the main www.lingsync.org main page (or from an obvious subpage like FAQs). If it is already linked from there, I was unable to find it. Can we make it easier to find this?

**Comment by jrwdunham** [comment]
d'oh, I should have read your (@cesine) last post directed at @HughP: I've made the spelling corrections at https://github.com/OpenSourceFieldlinguistics/FieldDBWebServer/edit/master/public/privacy.html#L58. Not clear to me when they'll take effect though...

**Comment by jrwdunham** [comment]
Ok, I've made a couple of other minor spelling corrections.

**Comment by jrwdunham** [comment]
@cesine Ok, this privacy page at https://www.lingsync.org/privacy.html does clear things up for me. I'm glad we have that up there. However, as I said, I think it needs to be easier to find.

@cesince @HughP perhaps one might interpret the corpus-specific autoglossers that LingSync generates as one type of derivative work that we do generate. Are there potential issues with ownership over the autoglossers produced using private corpora that we should be thinking about? Just a thought.

**Comment by HughP** [comment]
Well, if in the process of working with corpora of hundreds of languages, a better way to analyze content is produced, then I am not sure if that is derivative, or if that is "our experience".

**Comment by HughP** [comment]
Just an FYI: In several of my project I have had discussions of services policies and what they should include with respect to data statements. I started a public checklist here: https://github.com/HughP/Linguistics-Services-Policies . It is nowhere near complete yet, and I haven't even added all the things I have come across in my other projects. But at ILDC4 there were several presentations which seem that they would benefit from clearer thinking on this issue, as it get confusing quickly. So I thought I would start a check list of sorts. Fork and PR as you see fit.

**Comment by cesine** [comment]
ak lots of activity. thanks guys for caring about this :) 

@jrwdunham currently none of the devs are responsible for the website content, its usually the responsibility of the interns who are currently all doing data entry and analysis... i know it was rebuilt by tobin twice, each time to make it simpler and reduce content so that users don't get confused. I suspect it was removed on purpose because the privacy policy used to be linked on the old site: https://wwwdev.lingsync.org/#/technology @jrwdunham please put hugh's questions on your agenda for next meeting with the PIs. If they want you to modify the website, you can just edit the lingsync_site branch the same way you have done with the text. I also think parts of the bibliography #1279  would be nice on the website so that people like hugh with detailed questions could find some more text to read.

In any case, I think the quick and correct solution is also to add a slide to your slide decks. there will always be a small vocal minority who will come to your talk with doubts about why we made yet another database app... 

* free
* open source
* non proprietary
* open ended
* community driven

@jrwdunham  the current glossers are governed by the same permission system as the corpus, if the users want to share their glosser, they can by giving a user access to their glosser. they can also export it and email/dropbox it to someone. if they don't want to share they glosser, they don't. i know you're trying to help clarify what other derivative things could be, but I don't get why anything should be different. users manage who has access to their stuff, they manage their own licensing, and they manage their own terms of use. that seems really simple, straightforward and normal to me. no loopholes, no backdoors. no exceptions. users can export their data at any time and do whatever they want with it, including creating derivative stuff, and they decide how that derivative is licensed we have nothing to do with this.

@HughP 's list might help us follow what others are doing. @jrwdunham and I are kind of busy now trying to deliver code so we don't have a lot of time to dedicate to helping with this. we have a few bits of info listed around the project in the wiki, issues, dev blog white paper and who knows where else. you can fish in there if you have time. we also have some highlighted pdfs in a dropbox folder which contains  all the other software and articles we have read and cite in the CAML paper and other publications. you can look in there too https://www.dropbox.com/sh/i597yo03706mlbb/AAD21K-kZtdX3ehbW9eJBX8Qa?dl=0

**Comment by HughP** [comment]
Two remarks:

1. The bibliography on the site would be a great idea. I did some site modeling work about 2 years ago for the SIL FLEx product, and I included a Bibliography on that site see it here: http://flex.hughandbecky.org/reviews/
2. Let me offer perhaps a clear-cut case of derivative knowledge from a service. I will use the PELDA service mentioned in the web services list here:https://github.com/HughP/LinguisticsLibrarianList/blob/master/LinguisticWebServices.md
In that service a user can upload audio data. The audio data is then "scanned" for and attempts to return a phoneme or phonetic transcription.  Basic speech to text kinds of stuff. However the algorithm has the potential to get smarter with every test corpus uploaded. For instance, currently according to the presentation at ILCDC4 Blackfeet audio data is being used and they are searching for /h/. However, if we look at /h/ in [eng], [spa], [deu], and 12 other languages, we will have a lot more knowledge about the cross-linguistic transitions around the production of /h/. Now the service providers could tune their refinements of /h/ based on user corrections of the transcript provided back to the user. This is much like how facebook will sometimes present a user false information so that it can be verified as false. So, in the case of PELDA they can test the accuracy on the bases of a single user, the users of a single language, or a cross-linguistics pool of users. A platform which does that is really powerful, when it is fully operational, for a variety of reasons. Here is why, users, while receiving transcriptions of /h/ and enjoying those benefits, are simultaneously refining the very algorithm providing them "service". This new knowledge generated about the accuracy of the algorithm as provided by the users' feedback in the transcription process is not necessarily covered in the "terms of data return".  Meaning new knowledge was generated based on the provided data but that new knowledge is not destroyed when the user leaves the service and the data is "returned" to the user.  As an example lets say that some users of the PELDA service had a Pashto corpus and uploaded it and were contributing to revisions on the algorithm based on fixing transcriptions of Pashto. Now the service provider could choose to do some "tests" with the algorithm applied to the data, unbenounced to the user (or even via a pop-up box). Test which refine the algorithm (perhaps for dialectical reasons). However, an algorithm which can determine dialects of Pashto might have some other parties who are interested in it other than just the service providers. This often equates to monetary value. So, by offering a service to one set of customers, a product is formed which can then be leveraged to a different set of customers. That second product is not necessarily returned with the users "data", because it is strictly speaking not the users data, unless one argues that all the transcription corrections were the users actually working to produce more accurate algorithm. I hope this helps give a solid use case to why derivative knowledge claims and handling might be important in the future.

**Comment by cesine** [comment]
1. very cool!  let's see what the PIs think :)

2. your example is perfect, but its still something the corpus teams must document about their own projects if they are building derivative knowledge from their data sources. Can you help turn your example into a sample derivative context for teams (or contact the PELDA team to ask for their wording):  the links of where to put it are in here https://github.com/OpenSourceFieldlinguistics/FieldDB/issues/1906#issuecomment-77361731

i can copy paste it here with TODOs so you can see where it goes:

```
module.exports = {
  "_id": "corpus",
  "title": "Private Corpus",
  "titleAsUrl": "private_corpus",
  "description": "The details of this corpus are not public.",
  "couchConnection": {},
  "termsOfUse": {
    "humanReadable": "Sample: The materials included in this corpus are available for research and educational use. If you want to use the materials for commercial purposes, please notify the author(s) of the corpus (myemail@myemail.org) prior to the use of the materials. Users of this corpus can copy and redistribute the materials included in this corpus, under the condition that the materials copied/redistributed are properly attributed.  Modification of the data in any copied/redistributed work is not allowed unless the data source is properly cited and the details of the modification is clearly mentioned in the work. Some of the items included in this corpus may be subject to further access conditions specified by the owners of the data and/or the authors of the corpus."
  },
  "license": {
    "title": "Default: Creative Commons Attribution-ShareAlike (CC BY-SA).",
    "humanReadable": "This license lets others remix, tweak, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms. This license is often compared to “copyleft” free and open source software licenses. All new works based on yours will carry the same license, so any derivatives will also allow commercial use. This is the license used by Wikipedia, and is recommended for materials that would benefit from incorporating content from Wikipedia and similarly licensed projects.",
    "link": "http://creativecommons.org/licenses/by-sa/3.0/"
  },
"derivative_license":{
 "title": "Default: Sample derivative knowledge license",
    "humanReadable": "TODO put some sample derivaitve explanation and or sample license here",
    "link": "TODO link to sample"
},
  "copyright": "Default: Add names of the copyright holders of the corpus.",
  "pouchname": "",
  "datumFields": [{
    "label": "judgement",
    "value": "",
    "mask": "",
    "encrypted": "",
    "shouldBeEncrypted": "",
    "help": "Grammaticality/acceptability judgement of this data.",
    "size": "3",
    "showToUserTypes": "linguist",
    "userchooseable": "disabled"
  }, {
    "label": "gloss",
    "value": "",
    "mask": "",
    "encrypted": "",
    "shouldBeEncrypted": "checked",
    "help": "Metalanguage glosses of each individual morpheme (morphemes are pieces ofprefix, suffix) Sample entry: friend-fem-pl",
    "showToUserTypes": "linguist",
    "userchooseable": "disabled"
  }, {
    "label": "syntacticCategory",
    "value": "",
    "mask": "",
    "encrypted": "",
    "shouldBeEncrypted": "checked",
    "help": "This optional field is used by the machine to help with search.",
    "showToUserTypes": "machine",
    "userchooseable": "disabled"
  }, {
    "label": "syntacticTreeLatex",
    "value": "",
    "mask": "",
    "encrypted": "",
    "shouldBeEncrypted": "checked",
    "help": "This optional field is used by the machine to make LaTeX trees and help with search and data cleaning, in combination with morphemes and gloss (above). Sample entry: Tree [.S NP VP ]",
    "showToUserTypes": "machine",
    "userchooseable": "disabled"
  }, {
    "label": "tags",
    "value": "",
    "mask": "",
    "encrypted": "",
    "shouldBeEncrypted": "",
    "help": "Tags for constructions or other info that you might want to use to categorize your data.",
    "showToUserTypes": "all",
    "userchooseable": "disabled"
  }, {
    "label": "validationStatus",
    "value": "",
    "mask": "",
    "encrypted": "",
    "shouldBeEncrypted": "",
    "help": "Any number of tags of data validity (replaces DatumStates). For example: ToBeCheckedWithSeberina, CheckedWithRicardo, Deleted etc...",
    "showToUserTypes": "all",
    "userchooseable": "disabled"
  }],
  "sessionFields": [{
    "label": "dialect",
    "value": "",
    "mask": "",
    "encrypted": "",
    "shouldBeEncrypted": "",
    "help": "You can use this field to be as precise as you would like about the dialect of this session.",
    "userchooseable": "disabled"
  }, {
    "label": "language",
    "value": "",
    "mask": "",
    "encrypted": "",
    "shouldBeEncrypted": "",
    "help": "This is the langauge (or language family), if you would like to use it.",
    "userchooseable": "disabled"
  }, {
    "label": "dateElicited",
    "value": "",
    "mask": "",
    "encrypted": "",
    "shouldBeEncrypted": "",
    "help": "This is the date in which the session took place.",
    "userchooseable": "disabled"
  }],
  "comments": []
};
```
