### ISSUE TITLE
Test dative beta

### ISSUE THREAD

**Issue by louisa-bielig** [FieldDB/FieldDB#1984]
![lingsync bug - cannot edit partially created datum](https://cloud.githubusercontent.com/assets/4334000/7737802/62c08654-ff4e-11e4-9de6-0700bd9fc227.PNG)

@jrwdunham Hi Joel, I made myself a testing user for the dative beta. It looks great! When I find bugs while testing I will leave them here.

**Comment by jrwdunham** [comment]
@louisa-bielig Thanks so much! I'll be monitoring this.
