### ISSUE TITLE
How to Auto deploy with travis

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#2025]
Once you have finished with #2011 you now have all you need to get travis to automagically deploy your #2022  todo app to your #1999  

This wont be easy, it will require some trial and error, and some googling

Example of tutorials with keywords "travis github pages"
https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db
http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/

**Comment by vronvali** [comment]
@cesine need help with script to be able to use

**Comment by cesine** [comment]
script is here https://github.com/vronvali/mytodo-gulp/blob/master/deploy-ghpages.sh
