### ISSUE TITLE
specific confidence range for cleaning a lexicon

### ISSUE THREAD

**Issue by louisa-bielig** [FieldDB/FieldDB#2027]
![large amount of lexicon nodes](https://cloud.githubusercontent.com/assets/4334000/8440373/14df8f36-1f72-11e5-86c1-0d16f793064a.PNG)

(for cleaning a corpus, low-confidence morphemes are more interesting than high-confidence ones)

**Comment by HughP** [comment]
Just curious, what constitutes "cleaning"?

**Comment by louisa-bielig** [comment]
Hi Hugh,

"cleaning" the corpus constitutes checking if all nodes that are analyzed as morphemes are actually morphemes, and if they have the right glosses. 

Here is a small excerpt from From CAML 2012 on why the cleaning tools are useful (https://github.com/OpenSourceFieldlinguistics/FieldDB/blob/master/docs/CAML/caml2012.pdf?raw=true)

Section 3.1.1
Since a fundamental part of fieldwork is exploring and re-analyzing
data, LingSync allows users to create bots which partly automate cleaning tasks. Bots can even be
scheduled to run periodically on the corpus, as shown in (9a), reducing the manual data cleaning
process if, for example, the team decides partway through creating a database that all data should
use the convention PAST should be glossed as PERF in the context of ASP. Bots are able to go
through a corpus, and leave comments on data which should be cleaned manually, or even execute
the changes (9b) after the team has reviewed and approved the changes.

Section 3.1.4
Even “a funding body like the ELDP cannot get all of its grantees to deposit in an archive in a timely fashion (or at all)” (Thieberger,
2012). As part of the process of preparing data for publication involves collaboration of what
data needs to be cleaned or excluded, we hope that providing sharing, cleaning and collaboration
features directly integrated in the database will make this process easier for teams.
