### ISSUE TITLE
Switching-between-users related issues 

### ISSUE THREAD

**Issue by hisakonog** [FieldDB/FieldDB#2055]
#1987 
@cesine I think these issues may be partly due to the fact that I switch users on the same machine.  In real use cases, each user will most likely work on their own computer, and there will be few cases different users work on one and the same computer (e.g. shared lab computer).  I'll anyway test these issues once I have access to multiple machines.

**Comment by hisakonog** [comment]
Comments from June 3 #1987 

 - [ ] Read-only user (with no admin, writer, commenter role) should see Read-only view 

You add a new Read-only user (call him X) to a corpus (call the corpus Y). 
When X opens the corpus Y **for the first time** , X has Edit view. In order for X to have Read-only view, X needs to refresh page: 
Either 
- Switch between users, or 
- Admin adds other users to the same corpus (I think this is more likely the cause then switching users)

causes Read-only users to regain Edit view, and they have to reload page to only have read-only view.   


 - [ ] removing someone from admin should not give them editable corpus setting page view 

A user removed from admin permission could still have the editable view of the corpus setting page. Although they can not add another user (they get "You don't have permission to perform this action"), they can still edit the corpus name and description. They need to reload the page to not have access to editable view. 


 - [ ] Admin users consistently have editable corpus setting page 

Switching between Admin and non-Admin users causes Admin users to not see editable corpus setting page. 

 - Admin<sub>1</sub> > Admin<sub>2</sub> : Admin<sub>2</sub> has editable corpus setting view
 - Admin > non-Admin : non-Admin has editable corpus setting view until he reloads page
 - non-Admin > Admin : Admin is told he has no Admin permission until he reloads page 

Note on Reloading page: It does not have to be the corpus setting page. Users can reload any of the Corpus list, Data Entry and Corpus Setting pages and they will have the right view for their permissions.

**Comment by cesine** [comment]
louisa found and fixed an important bug a couple of weeks ago involving page load and permissions so maybe this is fixed
