### ISSUE TITLE
release notes for spreadsheet version 3.6.1.23.49

### ISSUE THREAD

**Issue by louisa-bielig** [FieldDB/FieldDB#2058]
see #1987

**Comment by cesine** [comment]
@louisa-bielig how is this going? can you do it before our meeting on wednesday?

**Comment by louisa-bielig** [comment]
Changes to spreadsheet app:

1. Added a "Leave" Corpus" and "Delete corpus" button and updated the FAQ to explain their effect

2. Hid the team members to decrease loading time - the team can now be loaded and then updated by the user

3. Added the ability to change number of fields (add or remove fields) for all datums

4. Show each corpus through its unique identifier (author + corpus tidentifier) on the corpus list page

We changed the corpus list page from just displaying the corpus title to the author + the corpus identifier. This combination provides a unique identifier for each corpus, which reduces the loading time of the list of corpora (which can be slow if you have access to many corpora).
