### ISSUE TITLE
Beta test new public urls pages

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#2138]
Hi everyone, This year we changed the search results on the public pages to use react/redux so we could render the same code both server side and client side. 

Before we post the 5th birthday on facebook, can you guys test these links and leave any bugs or strange screenshots you find on this issue

Sample corpora
* Sample formatted description: https://www.example.org/mecathcart/mecathcart-impulsatives/search/utterance:tt
* Sample audio/image search results: https://www.example.org/community/community-georgian/search/orthography:%E1%83%95%E1%83%98%E1%83%AA%E1%83%98
* Sample parallel text corpus: https://www.example.org/gina/gina-inuktitut/search/morphemes:lu
* Sample large datum: https://www.example.org/batumi/batumi-sarchelebi/search/orthography:%E1%83%90%E1%83%A0

- [x] Searching for any string that is in the corpus should work
- [x] Activity heat-map is only showing one year
- [x] Descriptions should support markdown formatting
- [x] some corpora are missing the map reduce for indexing
- [x] really large corpora result in an indexing error because the data exceeds elastic search request body max size
- [x] OR and AND arent working in the new search indices
- [x] really large documents render too slowly in IGT
- [ ] some parallel text fields arent set up in inuktitut db
- [ ] some db are indexing (speechrec)

Future
* use the contextualizer to add support for multilingual titles

**Comment by hisakonog** [comment]
Community Georgian: mp3 and/or jpg files missing in two datums "Please repeat 3 times" and "I don't have any".  Broken src links?

**Comment by Kedersha** [comment]
Hi! I might be missing something--are the sample copora links supposed to work for people who aren't signed in? I get a "page not found" error for all of them.

**Comment by cesine** [comment]
@Kedersha thanks! we didnt get any notifications that it was down :( we are still looking into the root cause in #2140 and will add more details in there.

Its back up now.

**Comment by cesine** [comment]
@hisakonog i re-imported the 2 utterances which were showing broken links in community-georgian

**Comment by cesine** [comment]
done! https://www.facebook.com/LingSyncApp
