### ISSUE TITLE
Prepare release for low resource language speech recognition android app

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#2152]
We need to prepare a new release that supports runtime permissions and uses URL connections instead of Apache http client.

- [x] verify user can record training utterances
- [x] verify user can register
- [x] verify activities

<img width="1121" alt="screen shot 2018-01-04 at 11 10 58 am" src="https://user-images.githubusercontent.com/196199/34560984-02ba3c50-f140-11e7-9221-9257eead33f4.png">

- [x] verify uploads
- [x] verify user can add new utterances
- [x] verify user can record video
- [x] verify user can add images
- [x] verify user can add audio
- [x] verify key signing for both lib and app
 
Test using
- [x] tablet
- [x] 4.1 
- [x] 4.2
- [x] 4.4 
- [x] 5.x 
- [x] 6.x 
- [x] 7.x 
- [x] 8.x

<img width="955" alt="screen shot 2018-01-02 at 11 41 40 am" src="https://user-images.githubusercontent.com/196199/34482751-f03170ec-efb1-11e7-8df3-7ceda307f1b3.png">

<img width="956" alt="screen shot 2018-01-02 at 11 43 25 am" src="https://user-images.githubusercontent.com/196199/34482785-2dc76718-efb2-11e7-8036-61dd7f3c0805.png">

Test upgrade using

<img width="157" alt="screen shot 2018-01-02 at 11 34 50 am" src="https://user-images.githubusercontent.com/196199/34482617-0214b806-efb1-11e7-943b-7bfcda8a3539.png">

  Bug list

- [x] icons arent showing in the menu (needed to use app instead of android)
- [x] turning off audio is not intuitive (this was because the icon wasnt showing and the ifRoom wasnt being respected)
- [x] playback audio doesnt work
- [x] icon isnt the kartuli icon?
- [ ] graceful retries after asking for permissions
- [x] Add your own words is in english
- [x] Welcome is in english
- [x] Recognizer doesnt copy to clipboard?

Last steps
- [x] edit config to go to the main acra db

  
  
<img width="1696" alt="screen shot 2018-08-26 at 5 15 59 pm" src="https://user-images.githubusercontent.com/196199/44633050-bf337380-a953-11e8-9dc1-471093ce16ec.png">

**Comment by MatMath** [comment]
Kartuli works on 4.4, permission too

**Comment by cesine** [comment]
We rejected Kartuli Speech Recognizer, with package name com.github.opensourcefieldlinguistics.fielddb.speech.kartuli, for violating our Malicious Behavior or User Data policy. If you submitted an update, the previous version of your app is still available on Google Play.

This app uses software that contains security vulnerabilities for users or allows the collection of user data without proper disclosure.

Below is the list of issues and the corresponding APK versions that were detected in your recent submission. Please upgrade your app(s) as soon as possible and increment the version number of the upgraded APK.

VulnerabilityAPK Version(s)Past Due DateSSL Error Handler

For more information on how to address WebView SSL Error Handler alerts, please see this Google Help Center article.

10November 30, 2016

SQL Injection

Your app(s) are using a content provider that contains a SQL Injection vulnerability.

To address this issue, follow the steps in this Google Help Center article.

10November 23, 2018

To confirm you’ve upgraded correctly, submit the updated version of your app to the Play Console and check back after five hours to make sure the warning is gone.

While these vulnerabilities may not affect every app that uses this software, it’s best to stay up to date on all security patches. Make sure to update any libraries in your app that have known security issues, even if you're not sure the issues are relevant to your app

**Comment by cesine** [comment]
closed in https://github.com/FieldDB/AndroidLanguageLessons/pull/16
