### ISSUE TITLE
Guidelines for corpus creation/verification

### ISSUE THREAD

**Issue by gretchenmcc** [FieldDB/FieldDB#735]
Just read an interesting post on a potential peer review process for language corpora that has some useful guidelines/suggestions http://www.paradisec.org.au/blog/2012/11/counting-collections/

**Comment by nthieberger** [comment]
We have written up the article on corpus/collections review and it will appear in the Australian Journal of Linguistics in early 2016

**Comment by vronvali** [comment]
That's great news!

**Comment by nthieberger** [comment]
A pre-publication copy is available here: http://paradisec.org.au/CorporaResearchOutput.pdf
