### ISSUE TITLE
When you join the project, protect yourself from github spamming you :)

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#834]
GitHub sends you an email everytime an issue gets updated. This is pretty ridiculous because issues on fieldb get updated every few days, especially on Thursdays when the interns are working. 

So rather than getting spammed, @gretchenmcc has made a lovely diagram to show you how to turn off the "spam" and keep only the emails when someone @ mentions you  :)

Here it is: 
https://docs.google.com/drawings/d/1D8FYP4xquPhsfSWt_a5fEfz62_xu0U5Dd22S7kI26qI/edit

**Comment by louisa-bielig** [comment]
Here is an updated version of Gretchen's diagram, since Github looks slightly different now:
![image](https://cloud.githubusercontent.com/assets/4334000/9366576/8174f2c2-46b8-11e5-817d-2c52aa85fc8f.png)
